### ISSUE TITLE
Warum kommt bei maven eigentlich dieser fehler wenn man versucht die dependency zu laden

### ISSUE THREAD

**Issue by FPowerkeks** [bytemcnetzwerk/minestom#24]
org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-depchain:jar:3.1.4 was not found in https://jitpack.io during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of jitpack has elapsed or updates are forced

**Comment by HttpMarco** [comment]
Fixed.
